export enum AppView {
  DASHBOARD = 'DASHBOARD',
  CONTROLE_CHEQUES = 'CONTROLE_CHEQUES',
  GESTAO_BOLETOS = 'GESTAO_BOLETOS',
  CONTROLE_BOLETOS = 'CONTROLE_BOLETOS',
  TITULOS_PRORROGADOS = 'TITULOS_PRORROGADOS',
  PREVISAO_FINANCEIRA = 'PREVISAO_FINANCEIRA',
  PAGAMENTOS_DIARIOS = 'PAGAMENTOS_DIARIOS',
  PREVISAO_FABRICA = 'PREVISAO_FABRICA',
  PREVISAO_CRISTIANO = 'PREVISAO_CRISTIANO',
  PAGAMENTOS_FABRICA = 'PAGAMENTOS_FABRICA',
  PAGAMENTOS_CRISTIANO = 'PAGAMENTOS_CRISTIANO',
  CADASTRO_CONTAS_BANCARIAS = 'CADASTRO_CONTAS_BANCARIAS',
  GERENCIADOR_CARTOES = 'GERENCIADOR_CARTOES',
  FECHAMENTO_PERIODO = 'FECHAMENTO_PERIODO',
  CONFIGURACAO_SEGURANCA = 'CONFIGURACAO_SEGURANCA',
}

// Data structure for a bank account
export interface ContaBancaria {
  id: string;
  titular: string;
  cnpj: string;
  pix: string;
  banco: string;
  agencia: string;
  contaCorrente: string; // Represents C/C
}